#include <array>
#include <chrono>
#include <cstdint>
#include <d3d11_1.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <DirectXMath.h>
#include <dxgi.h>
#include <filesystem>
#include <fmt/format.h>
#include <fstream>
#include <functional>
#include <malloc.h>
#include <memory>
#include <memory.h>
#include <SDKDDKVer.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_keyboard.h>
#include <SDL2/SDL_syswm.h>
#include <stdexcept>
#include <stdlib.h>
#include <tchar.h>
#include <type_traits>
#include <unordered_map>
#include <vector>
#include <windows.h>
#include <wrl.h>
#include "imgui.h"
